#!/bin/bash
# usage: 
# mmmfgrep "FPGA_*"
# mmmfgrep "FPGA_*" "*LED" "*Set"
# options: n(list number), i(ignorecase), I(no binary), r(recursive), 
#	   E(regexp) 
# change history
# 22-oct-2008
#	1. support extend-regexp (-E)
#	2. do not search for whole word (no -w)

set -x
if [ "$#" == "3" ]
then
   fgrep -rIin  "$1" * | fgrep -rIin  $2 --color=auto | fgrep -rIin  $3 --color=auto
elif [ "$#" == "2" ]
then
   fgrep -rIin  "$1" * | fgrep -rIin  $2 --color=auto 
else
   fgrep -rIin  "$1" * --color=auto
fi

